language: node_js
node_js:
  - "12"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/:_authToken=${NPM_PUBLISH_TOKEN}" >> ~/.npmrc
  - echo "@fs:registry=https://repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/" >> ~/.npmrc
    # because this is a weird monorepo and we cd into and out of directories, this is what worked for travis to publish
  - echo "//repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/:_authToken=${NPM_PUBLISH_TOKEN}" >> packages/react-scripts/.npmrc
  - echo "@fs:registry=https://repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/" >> packages/react-scripts/.npmrc
install:
  - "npm i"
  - "cd packages/react-scripts"
  - "npm i"
  - "cd ../../"
script:
  - npm test
  # test that a new app can be created with these scripts
  - mkdir -p ${HOME}/tmp && cd ${HOME}/tmp
  - npx create-react-app@3.2.0 fresh-cra-template --use-npm --scripts-version file:${TRAVIS_BUILD_DIR}/packages/react-scripts/
  - cd fresh-cra-template
  # this is necessary so we can do some additional npm installs in the freshCraTemplateUpdate.sh script
  - echo "//repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/:_authToken=${NPM_PUBLISH_TOKEN}" >> ${HOME}/tmp/fresh-cra-template/.npmrc
  - echo "@fs:registry=https://repo.churchofjesuschrist.org/artifactory/api/npm/npm-fhd/" >> ${HOME}/tmp/fresh-cra-template/.npmrc
  - CI=true npm test
  - npm run build
before_deploy: "cd ${TRAVIS_BUILD_DIR}/packages/react-scripts"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "dl-fh-eng-frontier@groups.ldschurch.org"
    api_key: "$NPM_PUBLISH_TOKEN"
    on:
      branch: frontierMaster
  - provider: script
    skip_cleanup: true
    script: cd ${TRAVIS_BUILD_DIR} && ./freshCraTemplateUpdate.sh
    on:
      branch: frontierMaster
# This tells travis to not build when the branch is master. This is important to have on our master
# branch as well because anytime we merge upstream changes from facebook, travis builds their whole matrix of 24 different builds.
# We do NOT need or want that to occur. Please leave this branches.except here, even on the master branch
branches:
  except:
    - master
