language: node_js
node_js:
  - 10
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//code.lds.org/artifactory/api/npm/npm-fhd/:_authToken=${NPM_PUBLISH_TOKEN}" >> ~/.npmrc
  - echo "@fs:registry=https://code.lds.org/artifactory/api/npm/npm-fhd/" >> ~/.npmrc
    # because this is a weird monorepo and we cd into and out of directories, this is what worked for travis to publish
  - echo "//code.lds.org/artifactory/api/npm/npm-fhd/:_authToken=${NPM_PUBLISH_TOKEN}" >> packages/react-scripts/.npmrc
  - echo "@fs:registry=https://code.lds.org/artifactory/api/npm/npm-fhd/" >> packages/react-scripts/.npmrc
install:
  - "npm i"
  - "cd packages/react-scripts"
  - "npm i"
  - "cd ../../"
script:
  - npm test
  # test that a new app can be created with these scripts
  - mkdir -p ${HOME}/tmp && cd ${HOME}/tmp
  - npx create-react-app my-test-app --use-npm --scripts-version file:${TRAVIS_BUILD_DIR}/packages/react-scripts/
  - cd my-test-app
  - CI=true npm test
  - npm run build
  - cd ${TRAVIS_BUILD_DIR}
before_deploy: "cd packages/react-scripts"
deploy:
  provider: npm
  skip_cleanup: true
  email: "dl-fh-eng-frontier@groups.ldschurch.org"
  api_key: "$NPM_PUBLISH_TOKEN"
  on:
    branch: frontierMaster
# This tells travis to not build when the branch is master. This is important to have on our master
# branch as well because anytime we merge upstream changes from facebook, travis builds their whole matrix of 24 different builds.
# We do NOT need or want that to occur. Please leave this branches.except here, even on the master branch
branches:
  except:
    - master