language: node_js
dist: jammy
node_js:
  - "20"
before_install:
  - git config --global url."https://git@".insteadOf git://
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - echo "//familysearch.jfrog.io/familysearch/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> ~/.npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/familysearch/api/npm/fs-npm-prod-virtual/" >> ~/.npmrc
    # because this is a weird monorepo and we cd into and out of directories, this is what worked for travis to publish
  - echo "//familysearch.jfrog.io/familysearch/api/npm/fs-npm-prod-virtual/:_authToken=${NPM_PUBLISH_TOKEN}" >> packages/react-scripts/.npmrc
  - echo "@fs:registry=https://familysearch.jfrog.io/familysearch/api/npm/fs-npm-prod-virtual/" >> packages/react-scripts/.npmrc
install:
  - npm install
script:
  - echo "Hello"
before_deploy: "cd ${TRAVIS_BUILD_DIR}/packages/react-scripts"
deploy:
  - provider: script
    edge: true
    cleanup: false
    script: echo "published "
    on:
      branch: fix-travis
# This tells travis to not build when the branch is master. This is important to have on our master
# branch as well because anytime we merge upstream changes from facebook, travis builds their whole matrix of 24 different builds.
# We do NOT need or want that to occur. Please leave this branches.except here, even on the master branch
branches:
  except:
    - master
